version: '3.1'
services:
    webserver:
        image: php:7.3-apache
        container_name: webserverlib
        volumes:
            - ./web:/var/www/html
            - ./logs:/var/log/apache2
            - ./conf/000-default.conf:/etc/apache2/sites-enabled/000-default.conf
            - ./conf/000-default.conf:/etc/apache2/sites-available/000-default.conf
            - ./conf/default-ssl.conf:/etc/apache2/sites-enabled/default-ssl.conf
            - ./conf/default-ssl.conf:/etc/apache2/sites-available/default-ssl.conf
            - ./conf/libanaabdul.crt:/etc/apache2/libanaabdul.crt
            - ./conf/libanaabdul.key:/etc/apache2/libanaabdul.key
            - ./scripts:/var/www/scripts
        ports:
            - "80:80"
            - "443:443"
        restart: always
        hostname: 127.0.0.1